name: Sync-repo

on:
  schedule:
    - cron: '0 0 * * *'  # 每天凌晨 0 点

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repository
        uses: actions/checkout@v3
        with:
          path: target  # 将目标仓库克隆到 'target' 目录

      - name: Checkout sync repository
        uses: actions/checkout@v3
        with:
          repository: ImLTHQ/edge-tunnel  # 要同步的仓库
          path: source  # 将要同步的仓库克隆到 'source' 目录

      - name: Sync files
        run: |
          rsync -av --delete source/ target/
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<actions@github.com>"

      - name: Commit and push changes
        run: |
          cd target
          git add .
          git commit -m "从上游同步" || echo "没有更改"
          git push origin main
